language: node_js
node_js:
- '6.9.1'


branches:
  only:
    - development

before_script:
  - npm install -g @angular/cli@1.3.1
  - npm i

script:
  - ng build --env=prod --base-href /

deploy:
  provider: s3
  access_key_id: $AWS_ACCESS_KEY_ID
  secret_access_key: $AWS_SECRET_ACCESS_KEY
  bucket: visualiza.tideapps.com
  skip_cleanup: true
  upload-dir: firstmakersblockly2_development
  local_dir: dist

notifications:
  email:
    on_failure: change
    on_success: change
